# Generated by Django 4.2.18 on 2025-02-23 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='extra_options/')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('select', 'Select'), ('text', 'Text'), ('number', 'Number')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.FloatField()),
                ('deep_time', models.FloatField()),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('extra_option_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_configurations.extraoptiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='jobtype_logos/')),
                ('inflation', models.FloatField()),
                ('base_pay', models.FloatField()),
                ('fixed_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='JobDataOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='price_configurations.jobdata')),
            ],
        ),
        migrations.AddField(
            model_name='jobdata',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='price_configurations.jobtype'),
        ),
        migrations.CreateModel(
            name='GeneralDataOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('general_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='price_configurations.generaldata')),
            ],
        ),
        migrations.AddField(
            model_name='extraoptiongroup',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_configurations.jobtype'),
        ),
        migrations.CreateModel(
            name='DataAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField()),
                ('amount', models.FloatField()),
                ('rate', models.FloatField()),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='price_configurations.generaldata')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_outputs', to='price_configurations.jobdata')),
            ],
        ),
    ]
