# Generated by Django 4.2.18 on 2025-03-28 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDataGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='extra_options/')),
                ('job_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_configurations.jobtype')),
            ],
        ),
        migrations.CreateModel(
            name='JobDataSelectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('display', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('internal_identifier', models.CharField(max_length=255)),
                ('job_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_configurations.jobtype')),
            ],
        ),
        migrations.CreateModel(
            name='JobPriceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='extraoptiongroup',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='generaldataoption',
            name='general_data',
        ),
        migrations.RemoveField(
            model_name='jobdataoption',
            name='job_data',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='deep_time',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='extra_option_group',
        ),
        migrations.RemoveField(
            model_name='jobdata',
            name='time',
        ),
        migrations.AddField(
            model_name='jobdata',
            name='type',
            field=models.CharField(choices=[('select', 'Select'), ('text', 'Text'), ('number', 'Number')], default='select', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_configurations.jobtype'),
        ),
        migrations.DeleteModel(
            name='DataAutomation',
        ),
        migrations.DeleteModel(
            name='ExtraOptionGroup',
        ),
        migrations.DeleteModel(
            name='GeneralData',
        ),
        migrations.DeleteModel(
            name='GeneralDataOption',
        ),
        migrations.DeleteModel(
            name='JobDataOption',
        ),
        migrations.AddField(
            model_name='jobpriceoption',
            name='job_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_price_options', to='price_configurations.jobdata'),
        ),
        migrations.AddField(
            model_name='jobpriceoption',
            name='job_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_price_options', to='price_configurations.joblevel'),
        ),
        migrations.AddField(
            model_name='jobdataselectoption',
            name='job_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_data_select_options', to='price_configurations.jobdata'),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='job_data_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_configurations.jobdatagroup'),
        ),
    ]
