# Generated by Django 4.2.18 on 2025-03-30 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_configurations', '0002_jobdatagroup_jobdataselectoption_joblevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='internal_identifier',
            field=models.CharField(default='select', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdata',
            name='placeholder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdata',
            name='required',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblevel',
            name='bundle_discount',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobdataselectoption',
            name='display',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='JobFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_interval', models.FloatField()),
                ('display', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
                ('job_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_configurations.jobtype')),
            ],
        ),
    ]
